DSS/Controllers/DetailsController.cs
using DSS.Data;
using DSS.Models;
using DSS.Repository;
using DSS.Repository.CommentRepository;
using DSS.Repository.Detail;
using DSS.Repository.Sessions;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace DSS.Controllers;

public class DetailsController : Controller
{
    private readonly IDetailRepository _detailRepository;
    private readonly ICommentRepository _commentRepository;
    private readonly IAccountRepository _accountRepository;
    private readonly INewsRepository _newsRepository;
    

    public DetailsController(INewsRepository newsRepository, IDetailRepository detailRepository,
        ICommentRepository commentRepository, IAccountRepository accountRepository)
    {
        _newsRepository = newsRepository;
        _detailRepository = detailRepository;
        _commentRepository = commentRepository;
        _accountRepository = accountRepository;
    }

    public async Task<IActionResult> Index(int newsId)
    {
        var sessionFlag = HttpContext?.Session?.GetString("username") == null;
        ViewBag.SessionFlag = sessionFlag;

        NewsModel isNewsNull = await _newsRepository.getNewsById(newsId);
        if (isNewsNull == null)
        {
            return RedirectToAction("Index", "Home");
        }

      

        NewsModel news = await _detailRepository.GetByIdAsync(newsId);

        var detailDto = new DetailDTO();
        detailDto.news = news;
        IEnumerable<CommentModel> comments = await _commentRepository.getCommentsByNewsIdAsync(newsId);
        detailDto.comments = comments.Reverse();
        detailDto.currentUser = _accountRepository.getSesionUser(HttpContext.Session.GetString("username"))?.Result;

       


        return View(detailDto);
    }

    [HttpPost]
    public IActionResult Index(string content, int newsId)
    {
        var user = HttpContext.Session.GetString("username");
        if (user == null) return RedirectToAction("Index");


        var newComment = new CommentModel();
        newComment.Content = content;
        newComment.UserModel = _accountRepository.getSesionUser(HttpContext.Session.GetString("username")).Result;
        newComment.NewsModel = _newsRepository.getNewsById(newsId).Result;

        _commentRepository.addComment(newComment);


        return RedirectToAction("Index");
    }

    [HttpPost]
    [Route("details/{currentUsername}/comments/remove/{id}")]
    public IActionResult removeComment(int id, string currentUsername)
    {
       
        if (HttpContext.Session.GetString("username") != currentUsername)
            return new JsonResult(new { status = "unsuccessful" });

        _commentRepository.removeCommentById(id);

        var result = new { status = "success" };
        return new JsonResult(result);
    }

    [HttpPost]
    [Route("details/{currentUsername}/news/remove/{id}")]
    public  IActionResult removeNews(int id, string currentUsername)
    {
        if (HttpContext.Session.GetString("username") != currentUsername)
            return new JsonResult(new { status = "unsuccessful" });
        
        var tempNews =  _newsRepository.getNewsById(id).Result;

        _newsRepository.RemoveNewsByNewsModel(tempNews);

        var result = new { status = "success" };

        return new JsonResult(result);
    }
}

DSS/Views/Details/Index.cshtml
@model DSS.Models.DetailDTO
@{
    ViewData["Title"] = @Model.news.Title;
}

<link href="~/css/detailsindex.css" rel="stylesheet"/>

<div class="blog-single gray-bg">
<div class="container mt-5">
<div class="row align-items-start">
<div class="col-lg-8">
    <article class="article box-shadow">

        @{
            if (@Model.news.ThumbnailImgUrl != null)
            {
                <div class="mb-4">
                    <img src="@Model.news.ThumbnailImgUrl" style="width: 100%;">
                </div>
            }
        }


        <h2 class="mb-2">
            @Model?.news.Title
            @{
                if (Model.currentUser?.Id == Model.news.UserModel.Id)
                {
                    <button class="btn btn-danger" onclick="removeNews(@Model.news?.Id, '@Model.currentUser.Username')">Delete</button>
                }
            }
        </h2>


        <div class="article-content">
            @Model.news.Content
        </div>

    </article>


    <div class="row d-flex mt-5">
        <h3 class="">Comments - @Model.comments.Count() </h3>
        <div class="card text-dark" id="comments-section">

            <div class="card-body p-4">

                @{
                    if (Model.comments.Count() == 0)
                    {
                        <p class="text-muted">No comment found, write the first comment</p>
                    }
                    foreach (var item in Model.comments)
                    {
                        <div>

                            <div class="ms-3">
                                <div class="d-flex flex-column ">
                                    <div >
                                        <div class="d-flex">
                                            <img class="rounded-circle "
                                                         src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?w=2000" alt="avatar" width="60"
                                                 height="60"/>
                                            <div class="d-flex flex-column ms-2 align-items-center ">

                                                <div class="d-flex align-items-center">
                                                    <h5 class="fw-bold mb-1 ">@item.UserModel.Username</h5>
                                                    @{
                                                        if (item.UserModel.Id == item.NewsModel.UserModel.Id)
                                                        {
                                                            <span class="badge bg-info">
                                                                Author
                                                            </span>
                                                        }
                                                        else
                                                        {
                                                            <span class="badge bg-primary">
                                                                Reader
                                                            </span>
                                                        }
                                                        if (item.UserModel.Id == Model.currentUser?.Id)
                                                        {
                                                            <button class="btn btn-danger" onclick="removeComment(@item?.Id, '@Model.currentUser?.Username')">Delete</button>
                                                        }




                                                    }

                                                </div>
                                                <p class="mb-0">
                                                    March 07, 2021

                                                </p>
                                            </div>


                                        </div>
                                    </div>
                                    <div class=" text-wrap ps-0 me-2">
                                        <p class=" mb-0 mt-2 text-wrap">
                                            @item.Content
                                        </p>

                                    </div>
                                </div>


                            </div>

                        </div>
                        <hr class="mt-5"/>
                    }
                }


            </div>


        </div>


    </div>
    <div class="contact-form article-comment" id="reply-section">
        <h4>Leave a Reply</h4>
        <form id="contact-form" method="POST" asp-controller="Details" asp-action="Index">
            <div class="row">
                <div class="col-md-12">
                    <div>
                        <textarea name="content" id="content" placeholder="Your message *" rows="4" class="form-control"></textarea>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="send">
                        <button class="px-btn" value="Index">
                            <span>Submit</span> <i class="arrow"></i>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>
<div class="col-lg-4 blog-aside">

    <div class="card" style="width: 100%; height: 25%;">
        <div class="card-body">
            <p class="card-title">Author</p>
        </div>

        <div class="card-body">
            <div class="d-flex gap-3 align-items-center">
                            <img src="https://img.freepik.com/free-vector/businessman-character-avatar-isolated_24877-60111.jpg?w=2000" style="width: 100px; height: 100px; border-radius: 180px;" class="card-img-top" alt="...">
                <h2>Hello I am @Model.news.UserModel.Username</h2>
            </div>
                        <p class="card-text mt-3"> d dolore dignissimos asperiores dicta facere optio quod commodi nam tempore recusandae. Rerum sed nulla eum vero expedita ex delectus voluptates rem at neque quos facere sequi unde optio aliquam!</p>
        </div>

    </div>

    
</div>
</div>
</div>
</div>

<script src="~/js/details.js"></script>